---

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------

- block:

    # Gather facts
    - include_tasks: gather_facts.yml

    # Gather users from /etc/group
    - include_tasks: get_host_access_control.yml

    # We get here on success
    - include_tasks: utils/set_fact_success.yml

  ignore_unreachable: true

  rescue:

    # Set unreachable status and fail
    - include_tasks: utils/set_fact_unreachable.yml
      when: result.unreachable is defined and result.unreachable == true

    # Set fail status and fail
    - include_tasks: utils/set_fact_failed.yml

  always:

    # Generate reports
    - include_tasks: generate_reports.yml
      when: host_access_control_reports_generate
