---

# ------------------------------------------------------------------------------
# SuSE - install package 
# ------------------------------------------------------------------------------

# Same as Redhat
- include_tasks: "../redhat/install.yml"
