---

# ------------------------------------------------------------------------------
# SuSE - remove package 
# ------------------------------------------------------------------------------

# Same as Redhat
- include_tasks: "../redhat/remove.yml"
