---

# ------------------------------------------------------------------------------
# SuSE - grab package version 
# ------------------------------------------------------------------------------

# Same as Redhat
- include_tasks: "../redhat/version.yml"
